#!/usr/bin/env python3
"""Generate champion costs and item/trait icons from Riot's Data Dragon.
Run from the repo root:  python scripts/gen_champion_map.py
"""
import json
import urllib.request
from pathlib import Path

DDRAGON = "https://ddragon.leagueoflegends.com"
OUT = Path(__file__).resolve().parents[1] / "frontend/src/lib/gameAssets.generated.ts"


def fetch_json(url: str):
    with urllib.request.urlopen(url) as resp:
        return json.load(resp)


def ts_record(name: str, value_type: str, mapping: dict) -> list[str]:
    lines = [f"export const {name}: Record<string, {value_type}> = {{"]
    for key in sorted(mapping):
        lines.append(f"  {json.dumps(key)}: {json.dumps(mapping[key])},")
    lines.append("}")
    return lines


def main() -> None:
    version = fetch_json(f"{DDRAGON}/api/versions.json")[0]
    champs = fetch_json(f"{DDRAGON}/cdn/{version}/data/en_US/tft-champion.json")["data"]
    items = fetch_json(f"{DDRAGON}/cdn/{version}/data/en_US/tft-item.json")["data"]
    traits = fetch_json(f"{DDRAGON}/cdn/{version}/data/en_US/tft-trait.json")["data"]

    costs = {entry["id"]: entry["cost"] for entry in champs.values()}

    item_base = f"{DDRAGON}/cdn/{version}/img/tft-item"
    item_icons = {e["id"]: f"{item_base}/{e['image']['full']}" for e in items.values()}

    trait_base = f"{DDRAGON}/cdn/{version}/img/tft-trait"
    trait_icons = {e["id"]: f"{trait_base}/{e['image']['full']}" for e in traits.values()}

    out = [
        "// AUTO-GENERATED by scripts/gen_champion_map.py - do not edit by hand",
        f"// Data Dragon version: {version}",
        "",
    ]
    out += ts_record("CHAMPION_COSTS", "number", costs) + [""]
    out += ts_record("ITEM_ICONS", "string", item_icons) + [""]
    out += ts_record("TRAIT_ICONS", "string", trait_icons)

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(out) + "\n")
    print(f"v{version}: {len(costs)} costs, {len(item_icons)} items, {len(trait_icons)} traits -> {OUT}")

if __name__ == "__main__":
    main()