#!/usr/bin/env python3
"""Generate the champion-id -> icon-URL map from Riot's Data Dragon.
Run from the repo root:  python scripts/gen_champion_map.py
"""

import json
import urllib.request
from pathlib import Path

DDRAGON = "https://ddragon.leagueoflegends.com"
OUT = Path(__file__).resolve().parents[1] / "frontend/src/data/champions.generated.ts"

def fetch_json(url: str):
    with urllib.request.urlopen(url) as resp:
        return json.load(resp)
    
def main() -> None:
    version = fetch_json(f"{DDRAGON}/api/versions.json")[0]
    champs = fetch_json(f"{DDRAGON}/cdn/{version}/data/en_US/tft-champion.json")["data"]
    base = f"{DDRAGON}/cdn/{version}/img/tft-champion"

    icons = {
        entry["id"]: f"{base}/{entry['image']['full']}"
        for entry in champs.values()
    }

    lines = [
        "// AUTO-GENERATED by scripts/gen_champion_map.py - do not edit by hand",
        f"// Data Dragon version: {version}",
        "export const CHAMPION_ICONS: Record<string, string> = {",
    ]
    for cid in sorted(icons):
        lines.append(f"   {json.dumps(cid)}: {json.dumps(icons[cid])},")
    lines.append("}")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines) + "\n")
    print(f"v{version}: wrote {len(icons)} champions -> {OUT}")

if __name__ == "__main__":
    main()