#!/usr/bin/env python3
"""Generate champion icons/costs and item icons from Riot's Data Dragon + Community Dragon.
Run from the repo root:  python scripts/gen_champion_map.py
"""
import json
import urllib.request
from pathlib import Path

DDRAGON = "https://ddragon.leagueoflegends.com"
CDRAGON = "https://raw.communitydragon.org/latest/game/assets/characters"
OUT = Path(__file__).resolve().parents[1] / "frontend/src/lib/gameAssets.generated.ts"


def fetch_json(url: str):
    with urllib.request.urlopen(url) as resp:
        return json.load(resp)


def ts_record(name: str, value_type: str, mapping: dict) -> list[str]:
    lines = [f"export const {name}: Record<string, {value_type}> = {{"]
    for key in sorted(mapping):
        lines.append(f"  {json.dumps(key)}: {json.dumps(mapping[key])},")
    lines.append("}")
    return lines


def main() -> None:
    version = fetch_json(f"{DDRAGON}/api/versions.json")[0]
    champs = fetch_json(f"{DDRAGON}/cdn/{version}/data/en_US/tft-champion.json")["data"]
    items = fetch_json(f"{DDRAGON}/cdn/{version}/data/en_US/tft-item.json")["data"]
    traits = fetch_json(f"{DDRAGON}/cdn/{version}/data/en_US/tft-trait.json")["data"]

    icons, costs = {}, {}
    for entry in champs.values():
        cid = entry["id"]
        set_suffix = entry["image"]["full"].rsplit(".", 2)[-2]
        slug = cid.lower()
        icons[cid] = f"{CDRAGON}/{slug}/hud/{slug}_square.{set_suffix.lower()}.png"
        costs[cid] = entry["cost"]

    item_base = f"{DDRAGON}/cdn/{version}/img/tft-item"
    item_icons = {
        entry["id"]: f"{item_base}/{entry['image']['full']}"
        for entry in items.values()
    }

    trait_base = f"{DDRAGON}/cdn/{version}/img/tft-trait"
    trait_icons = {
        entry["id"]: f"{trait_base}/{entry['image']['full']}"
        for entry in traits.values()
    }

    out = [
        "// AUTO-GENERATED by scripts/gen_champion_map.py - do not edit by hand",
        f"// Data Dragon version: {version}",
        "",
    ]
    out += ts_record("CHAMPION_ICONS", "string", icons) + [""]
    out += ts_record("CHAMPION_COSTS", "number", costs) + [""]
    out += ts_record("ITEM_ICONS", "string", item_icons) + [""]
    out += ts_record("TRAIT_ICONS", "string", trait_icons)

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(out) + "\n")
    print(f"v{version}: {len(icons)} champions, {len(item_icons)} items, {len(trait_icons)} traits -> {OUT}")

if __name__ == "__main__":
    main()